# wrangler.toml
name = "zoho-flow-dash"
pages_build_output_dir = "dist/public"

[vars]
# This is a placeholder, but good practice for env vars
WORKERS_LOG_LEVEL = "debug"

[[services]]
binding = "DATABASE"
service = "your-database-binding-name" # You'll set this up in Cloudflare UI if needed

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"